version: '3.8'
services:
  sentiment-model:
    build: 
      context: ./newsAlerter/model_service
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=${HF_TOKEN}
    platform: linux/arm64
    ports:
      - "8080:8080"
    environment:
      - HF_HOME=/root/.cache/huggingface
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - model-cache:/root/.cache/huggingface
      - model-offload:/app/offload
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '2.0'    # CPU limits go inside resources.limits
        reservations:
          memory: 6G
    # Optional: if you have multiple CPUs, allocate more
    cpus: 2.0           # Reduced from 4.0 to be more conservative
    # Add swap
    tmpfs:
      - /swap:size=8G

volumes:
  model-cache:
  model-offload:  # Add volume for model offloading 