version: '3.8'
services:
  newsalerter:
    build: 
      context: .
      dockerfile: src/functions/news_alerter/Dockerfile
    image: newsalerterfunction:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-1
      - LAMBDA_HANDLER=lambda_function.handler
    volumes:
      - ./src/functions/news_alerter:/var/task

  worker:
    build: 
      context: .
      dockerfile: src/functions/worker/Dockerfile
    image: workerfunction:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-1
      - LAMBDA_HANDLER=lambda_function.handler
    volumes:
      - ./src/functions/worker:/var/task

  handletable:
    build: 
      context: .
      dockerfile: src/functions/handle_table/Dockerfile
    image: handletablefunction:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-1
      - LAMBDA_HANDLER=lambda_function.handler
    volumes:
      - ./src/functions/handle_table:/var/task

  emailcontrols:
    build: 
      context: .
      dockerfile: src/functions/email_controls/Dockerfile
    image: emailcontrolsfunction:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-1
      - LAMBDA_HANDLER=lambda_function.handler
    volumes:
      - ./src/functions/email_controls:/var/task

volumes:
  model-cache:
  model-offload:  # Add volume for model offloading 