version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gargoylescope"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = [
    "NewsAlerterFunction=767397836855.dkr.ecr.us-west-1.amazonaws.com/newsalerterfunction",
    "WorkerFunction=767397836855.dkr.ecr.us-west-1.amazonaws.com/workerfunction",
    "HandleTableFunction=767397836855.dkr.ecr.us-west-1.amazonaws.com/handletablefunction",
    "EmailControlsFunction=767397836855.dkr.ecr.us-west-1.amazonaws.com/emailcontrolsfunction"
]
