version = 0.1
[default.deploy.parameters]
stack_name = "gargoylescope"
resolve_s3 = true
s3_prefix = "gargoylescope"
resolve_image_repos = true
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
