# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true
docker_network = "null"
container_env_var = []
docker_volume = ["model-cache:/var/task/model"]

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
docker_volume = ["model-cache:/var/task/model"]
parameter_overrides = "FunctionName=newsAlerter"
container_name = "newsAlerter"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
